[tool.poetry]
name = "coding-geeks-game-project"
version = "0.1.0"
description = ""
authors = ["vh24859 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
varname = "^0.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
